// import { Task } from "@/interfaces/task/task.interface";

// export const dataTasks: Task[] = [
//     {
//       id: "1",
//       planned: false,
//       title: "Cobertura - Cliente 1",
//       datePlanned: "",
//       start: "2024-01-08",
//       end: "2024-08-08",
//       client: "Nombre cliente",
//       documentId: "11.111.111-1",
//       type: "cobertura",
//       color: "#3b82f6",
//     },
//     {
//       id: "2",
//       planned: false,
//       title: "Línea de crédito - Cliente 2",
//       datePlanned: "",
//       start: "2024-01-15",
//       end: "2024-06-08",
//       client: "Nombre cliente",
//       documentId: "11.111.111-1",
//       type: "linea-credito",
//       color: "#14b8a6",
//     },
//     {
//       id: "3",
//       planned: false,
//       title: "Cotización - Cliente 3",
//       datePlanned: "",
//       start: "2024-04-10",
//       end: "2024-04-20",
//       client: "Nombre cliente",
//       documentId: "11.111.111-1",
//       type: "cotizacion",
//       color: "#f59e0b",
//     },
//     {
//       id: "4",
//       planned: false,
//       title: "Seguimiento Cotización - Cliente 4",
//       datePlanned: "",
//       start: "2024-04-25",
//       end: "2024-05-05",
//       client: "Nombre cliente",
//       documentId: "11.111.111-1",
//       type: "seguimiento-cotizacion",
//       color: "#8B5CF6",
//     },
//     {
//       id: "5",
//       planned: false,
//       title: "Cobertura - Cliente 5",
//       datePlanned: "",
//       start: "2024-06-01",
//       end: "2024-07-01",
//       client: "Nombre cliente",
//       documentId: "11.111.111-1",
//       type: "cobertura",
//       color: "#3b82f6",
//     },
//   ];